version: '3.7'
services:
    # MongoDB
    mongo:
        image: 'mongo:4.2.6-bionic'
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./mongodata:/data/db
        restart: always
    # Go App
    go-app:
        build: ./src
        container_name: goapp_segurito
        depends_on:
            - 'mongo'
        environment:
            - PORT=8000
        ports:
            - '8000:8000'
        volumes:
            - './src:/opt/src:cached'
    # Mongo Express Web-based MongoDB admin interface
    mongo_express:
        image: mongo-express
        container_name: mongo_express
        depends_on:
            - 'mongo'
        ports:
            - '8081:8081'
        restart: always
